
// This file is automatically generated by the Firebase setup.
// Do not edit this file manually.

import type { FirebaseOptions } from 'firebase/app';

// The Firebase configuration is now hardcoded to ensure successful initialization.
const firebaseConfig: FirebaseOptions = {
  "projectId": "studio-8694220525-70f3e",
  "appId": "1:974298549255:web:00f766e3dd5de0c0e92ea2",
  "apiKey": "AIzaSyDeW9cUWC5QZGIOY6_ElI2BBPs0c-jBx1c",
  "authDomain": "studio-8694220525-70f3e.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "974298549255"
};


export function getFirebaseConfig(): FirebaseOptions {
  if (!firebaseConfig.apiKey) {
    throw new Error('Missing apiKey in firebaseConfig');
  }
  return firebaseConfig;
};
